spring:
  application:
    name: todo_project_server

  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zhang.todo_project_server  # ? ??????????
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn